events {
    worker_connections 1024;
}

http {
    # Rutare pentru Grafana
    server {
        listen 80;
        server_name grafana.pulseguard.local;

        location / {
            proxy_pass http://pulseguard-grafana:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Suport WebSockets pentru Grafana Live
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Rutare pentru API (FastAPI)
    server {
        listen 80;
        server_name api.pulseguard.local;

        location / {
            proxy_pass http://pulseguard_api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
