name: PulseGuard CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Native Deployment on VAIO
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Containers
        run: |
          echo "==> Pornire redeploy pe VAIO..."
          docker compose down
          docker compose up -d --build
          docker image prune -f
          docker compose ps
